document.writeln("<!-- <!DOCTYPE HTML>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title></title>");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' href=\'style.css\'>");
document.writeln("</head>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'lib/bootstrap-3.3.7/dist/css/bootstrap.min.css\'> -->");
document.writeln("<style type=\'text/css\'>");
document.writeln("#Footer{");
document.writeln("	width: 65%;    background-color: #E8EDED;");
document.writeln("	margin:0 auto 30px;");
document.writeln("	text-align: center;");
document.writeln("	font-size: 12px;");
document.writeln("	color: #45565A;");
document.writeln("	padding-top: 8px;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<!-- <body> -->");
document.writeln("<div id=\'Footer\'>");
document.writeln("Copyright © Guangdong Ocean University MeiXian association 2017 All Rights Reserved</br>");
document.writeln("版权所有：广东海洋大学梅县同乡会</br>");
document.writeln("地址：中华人民共和国 广东省 湛江市 麻章区 海大路1号</br>　");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<!-- </body>");
document.writeln("</html> -->");