document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' href=\'lib/bootstrap-3.3.7/dist/css/bootstrap.min.css\'>");
document.writeln("<!-- 引入jQuery库 -->");
document.writeln("<script type=\'text/javascript\' src=\'lib/bootstrap-3.3.7/docs/assets/js/vendor/jquery.min.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'lib/bootstrap-3.3.7/dist/js/bootstrap.js\'></script>");
document.writeln("<style> ");
document.writeln("body{");
document.writeln("background:url(img/backgrm.png); ");
document.writeln("background-size: 100%;");
document.writeln("background-repeat:no-repeat;");
document.writeln("margin: 0;");
document.writeln("font-size: 12px;");
document.writeln("color: #45565A;");
document.writeln("position: relative;");
document.writeln("}");
document.writeln("body a{");
document.writeln("  font-size: 12px;");
document.writeln("  text-decoration: none;");
document.writeln("  color: #45565A;");
document.writeln("}");
document.writeln("body a:hover{");
document.writeln("  text-decoration: none;");
document.writeln("}");
document.writeln(".center{");
document.writeln("  position: relative;         /*background-color: #D7E1E3;*/");
document.writeln("}");
document.writeln("");
document.writeln(".nav{");
document.writeln("  width: 900px; height: 75px;");
document.writeln("  background-color: white;");
document.writeln("  margin: 0 auto;");
document.writeln("  box-shadow: 5px 8px 2px #B1C0C5;");
document.writeln("}");
document.writeln(".nav img{");
document.writeln("  float: left;");
document.writeln("  margin-left: 15px;");
document.writeln("}");
document.writeln(".nav table{");
document.writeln("  float: left;");
document.writeln("  margin-left: 75px;        /*border: 1px solid black;*/");
document.writeln("  padding: 0;");
document.writeln("  border-collapse:collapse;");
document.writeln("}");
document.writeln(".nav table tr{  /*行*/");
document.writeln("  height: 75px;");
document.writeln("  margin: 0;");
document.writeln("}");
document.writeln(".nav table td{");
document.writeln("  margin: 0px;              /*background-color: gray;*/");
document.writeln("}");
document.writeln(".nav a{");
document.writeln("  padding: 8px 25px 5px;");
document.writeln("  height: 30px;");
document.writeln("  display: block;");
document.writeln("  border-right: 1px solid #FE5C11;    /* background-color: red;*/");
document.writeln("}");
document.writeln("#orange{");
document.writeln("  background-color: #FE5C11;");
document.writeln("}");
document.writeln(".Img{");
document.writeln("  margin-top: 50px;");
document.writeln("}");
document.writeln(".Img img{");
document.writeln("  margin:0 auto;       /* background-color: red;*/");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div  class=\'center\' style=\'text-align: center;width: 900px;");
document.writeln("margin: 0 auto;padding: 0;\'>  <!-- 把所有的东西放在中间的模块 -->");
document.writeln("  <div class=\'nav\'>");
document.writeln("    <img src=\'img/logo.png\'>");
document.writeln("    <table>");
document.writeln("      <tr>");
document.writeln("        <td id=\'orange\'><a name=\'top\' style=\'color: white;\' href=\'index.php\'>首页</a></td>");
document.writeln("        <td><a href=\'message.php\'>乡会信息</a></td>");
document.writeln("        <td><a href=\'affiche.php\'>动态</a></td>");
document.writeln("        <td><a href=\'communication.php\'>沟通服务</a></td>");
document.writeln("        <!-- <td><a href=\'display.php\'>精彩展示</a></td> -->");
document.writeln("        <td><a href=\'recruit.php\'>换届招聘</a></td>");
document.writeln("        <td><a href=\'dispose/mng_identify.php\'>管理员操作</a></td>");
document.writeln("      </tr>");
document.writeln("    </table>");
document.writeln("  </div>");
document.writeln("");
document.writeln("  <div class=\'Img\'>");
document.writeln("    <img src=\'img/hand&word.png\'>");
document.writeln("  </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");