document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("");
document.writeln("<style> ");
document.writeln("#return_top{     /*border: 1px solid red;*/");
document.writeln("  position: absolute;");
document.writeln("  bottom: 10px;");
document.writeln("  right: 13%;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div>");
document.writeln("    <a href=\'#top\'><img id=\'return_top\' src=\'img/top.png\'></a>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");